name: FactionsPro
author: Sheep
description: Factions, Edit by SHEEP
version: 1.0
main: FactionsPro\FactionMain
api: [1.12.0,2.0.0]
commands:
  f:
    description: use /f help for all parameters
    permission: f.command
permissions:
  f.command:
    default: true
    description: "Allow use of all faction commands"
  f.override:
    default: op
    description: "Allows op users to override factions"
